export const CUSTOMER_SUCCESS_PERSONA_ID = "customer_success";
export const CLOUD_ARCHITECT_PERSONA_ID = "cloud_architect";
export const LEAD_DEVELOPER_PERSONA_ID = "lead_developer";

export const AZURE_RESOURCE_CANDIDATE_POOL = [
  "Azure Virtual Machines",
  "Azure Virtual Machine Scale Sets",
  "Azure Dedicated Host",
  "Azure Spot Virtual Machines",
  "Azure App Service",
  "Azure Functions",
  "Azure Kubernetes Service (AKS)",
  "Azure Container Apps",
  "Azure Container Instances",
  "Azure Spring Apps",
  "Azure Red Hat OpenShift",
  "Azure Service Fabric",
  "Azure Batch",
  "Azure Static Web Apps",
  "Azure Load Testing",
  "Azure Chaos Studio",
  "Azure Lab Services",
  "Azure Dev Box",
  "Azure VMware Solution",
  "Azure Virtual Network",
  "Azure Virtual WAN",
  "Azure VPN Gateway",
  "Azure ExpressRoute",
  "Azure Bastion",
  "Azure Firewall",
  "Azure DDoS Protection",
  "Azure Application Gateway",
  "Azure Front Door",
  "Azure Load Balancer",
  "Azure Traffic Manager",
  "Azure DNS",
  "Azure Private Link",
  "Azure Private Endpoint",
  "Azure NAT Gateway",
  "Azure Route Server",
  "Azure Network Watcher",
  "Azure Web PubSub",
  "Azure Content Delivery Network",
  "Azure Orbital",
  "Microsoft Entra ID",
  "Microsoft Entra ID Governance",
  "Microsoft Entra External ID",
  "Microsoft Entra Domain Services",
  "Azure Key Vault",
  "Azure Managed HSM",
  "Managed Identity for Azure resources",
  "Azure Confidential Ledger",
  "Azure Attestation",
  "Azure Policy",
  "Azure Resource Graph",
  "Azure Monitor",
  "Azure Log Analytics",
  "Azure Application Insights",
  "Microsoft Defender for Cloud",
  "Microsoft Sentinel",
  "Azure Backup",
  "Azure Site Recovery",
  "Recovery Services vault",
  "Azure Lighthouse",
  "Azure Advisor",
  "Azure Cost Management + Billing",
  "Azure Arc",
  "Azure Automation",
  "Azure Update Manager",
  "Azure Monitor SCOM Managed Instance",
  "Azure Storage account",
  "Azure Blob Storage",
  "Azure Files",
  "Azure Queue Storage",
  "Azure Table Storage",
  "Azure Data Lake Storage Gen2",
  "Azure NetApp Files",
  "Azure Elastic SAN",
  "Azure Managed Disks",
  "Azure Archive Storage",
  "Azure File Sync",
  "Azure SQL Database",
  "Azure SQL Managed Instance",
  "SQL Server on Azure Virtual Machines",
  "Azure Cosmos DB",
  "Azure Database for PostgreSQL Flexible Server",
  "Azure Database for MySQL Flexible Server",
  "Azure Database Migration Service",
  "Azure Cache for Redis",
  "Azure Managed Instance for Apache Cassandra",
  "Azure Service Bus",
  "Azure Event Grid",
  "Azure Event Hubs",
  "Azure API Management",
  "Azure Logic Apps",
  "Azure Data Factory",
  "Azure Data Share",
  "Azure Relay",
  "Azure Notification Hubs",
  "Azure Communication Services",
  "Azure Managed Grafana",
  "Azure Synapse Analytics",
  "Azure Databricks",
  "Azure HDInsight",
  "Azure Stream Analytics",
  "Azure Data Explorer",
  "Azure Analysis Services",
  "Azure Machine Learning",
  "Azure OpenAI Service",
  "Azure AI Search",
  "Azure AI Document Intelligence",
  "Azure AI Speech",
  "Azure AI Vision",
  "Azure AI Language",
  "Azure AI Content Safety",
  "Azure AI Translator",
  "Azure Bot Service",
  "Azure AI Video Indexer",
  "Azure Maps",
  "Azure Digital Twins",
  "Azure IoT Hub",
  "Azure IoT Central",
  "Azure IoT Operations",
  "Azure Time Series Insights Gen2",
  "Azure Media Services",
  "Azure Quantum",
  "Azure Fluid Relay",
  "Azure DevOps Services",
  "Azure Repos",
  "Azure Pipelines",
  "Azure Boards",
  "Azure Artifacts",
  "Azure Test Plans",
  "Azure Deployment Environments",
  "Azure Container Registry",
  "Azure Managed Prometheus",
  "Microsoft Purview",
  "Azure Resource Manager",
  "Azure Bicep",
  "ARM templates",
] as const;

export const DEVELOPER_STACK_CANDIDATE_POOL = [
  "TypeScript",
  "JavaScript",
  "Python",
  "Java",
  "C#",
  "Go",
  "SQL",
  "Kotlin",
  "PHP",
  "C++",
  "Rust",
  "Swift",
  "Dart",
  "Ruby",
  "Bash",
  "PowerShell",
  "Node.js",
  ".NET",
  "JVM",
  "CPython",
  "Deno",
  "Bun",
  "React",
  "Next.js",
  "Angular",
  "Vue.js",
  "Nuxt",
  "Svelte",
  "SolidJS",
  "Remix",
  "Astro",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Ant Design",
  "Chakra UI",
  "TanStack Query",
  "Redux Toolkit",
  "Zustand",
  "React Hook Form",
  "Zod",
  "Express",
  "NestJS",
  "Fastify",
  "Hono",
  "Django",
  "FastAPI",
  "Flask",
  "Spring Boot",
  "Micronaut",
  "Quarkus",
  "ASP.NET Core",
  "Laravel",
  "Symfony",
  "Ruby on Rails",
  "Phoenix (Elixir)",
  "Gin (Go)",
  "Echo (Go)",
  "Fiber (Go)",
  "Actix Web",
  "Axum",
  "gRPC",
  "GraphQL",
  "Apollo Server",
  "Hasura",
  "tRPC",
  "PostgreSQL",
  "MySQL",
  "MariaDB",
  "SQL Server",
  "SQLite",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "OpenSearch",
  "Apache Cassandra",
  "DynamoDB",
  "Snowflake",
  "ClickHouse",
  "InfluxDB",
  "Neo4j",
  "Prisma ORM",
  "TypeORM",
  "Sequelize",
  "Mongoose",
  "SQLAlchemy",
  "Django ORM",
  "Entity Framework Core",
  "Hibernate",
  "jOOQ",
  "Dapper",
  "Knex.js",
  "Apache Kafka",
  "RabbitMQ",
  "NATS",
  "Apache Pulsar",
  "Redis Streams",
  "Amazon SQS",
  "Celery",
  "BullMQ",
  "Docker",
  "Kubernetes",
  "Helm",
  "Terraform",
  "Pulumi",
  "Ansible",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "Argo CD",
  "FluxCD",
  "Istio",
  "Nginx",
  "Caddy",
  "Traefik",
  "Jest",
  "Vitest",
  "Playwright",
  "Cypress",
  "Testing Library",
  "Mocha",
  "Chai",
  "Pytest",
  "JUnit 5",
  "NUnit",
  "xUnit",
  "Postman",
  "Bruno",
  "OpenTelemetry",
  "Prometheus",
  "Grafana",
  "Loki",
  "Jaeger",
  "Sentry",
  "SonarQube",
  "OWASP ZAP",
  "Dependabot",
  "Renovate",
  "LangChain",
  "LlamaIndex",
  "Semantic Kernel",
  "OpenAI SDK",
  "Anthropic SDK",
  "Hugging Face Transformers",
  "vLLM",
  "MLflow",
  "Weights & Biases",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "PyTorch",
  "TensorFlow",
  "XGBoost",
  "React Native",
  "Flutter",
  "Kotlin Multiplatform",
  "SwiftUI",
  "Jetpack Compose",
] as const;

export const AZURE_RESOURCE_TOP_CHOICES = AZURE_RESOURCE_CANDIDATE_POOL.slice(0, 28);
export const DEVELOPER_STACK_TOP_CHOICES = DEVELOPER_STACK_CANDIDATE_POOL.slice(0, 36);

export const POPULARITY_RELIABILITY_BASIS =
  "Ordered by broad market adoption and production reliability (enterprise-first bias).";

export type SkillDomain =
  | "marketing"
  | "sales"
  | "product_management"
  | "data_analytics"
  | "security_privacy"
  | "legal_compliance"
  | "finance_strategy"
  | "operations_delivery"
  | "ux_research"
  | "customer_success"
  | "partnerships_growth"
  | "general_strategy";

export type PersonaCatalogType =
  | "azure_resources"
  | "developer_stack"
  | "academic_skills";

export interface PersonaWithCatalog {
  id: string;
  name: string;
  reason: string;
  initialThought: string;
  candidateCatalogType?: PersonaCatalogType;
  candidatePool?: string[];
  candidateTopChoices?: string[];
  rankingBasis?: string;
  skillDomain?: SkillDomain;
}

const ACADEMIC_SKILL_DOMAIN_KEYWORDS: Record<SkillDomain, readonly string[]> = {
  marketing: [
    "marketing", "brand", "branding", "content", "social media", "growth",
    "campaign", "funnel", "seo", "sem", "acquisition", "performance",
  ],
  sales: [
    "sales", "revenue", "account executive", "pipeline", "prospecting",
    "crm", "deal", "closing", "bdr", "quota", "territory",
  ],
  product_management: [
    "product", "roadmap", "backlog", "prioritization", "mvp", "feature",
    "go-to-market", "stakeholder", "requirements", "discovery", "launch",
  ],
  data_analytics: [
    "data", "analytics", "bi", "insight", "forecast", "modeling",
    "experiment", "causal", "dashboard", "metric", "kpi", "research",
  ],
  security_privacy: [
    "security", "privacy", "threat", "risk", "incident", "compliance security",
    "soc", "iso", "nist", "vulnerability", "pentest", "fraud",
  ],
  legal_compliance: [
    "legal", "compliance", "regulatory", "gdpr", "ccpa", "contract",
    "policy", "terms", "licensing", "intellectual property", "audit",
  ],
  finance_strategy: [
    "finance", "financial", "budget", "pricing", "unit economics", "cost",
    "margin", "valuation", "forecasting", "cash flow", "roi",
  ],
  operations_delivery: [
    "operations", "delivery", "program", "project management", "process",
    "supply chain", "sre", "reliability", "incident management", "sla",
  ],
  ux_research: [
    "ux", "ui", "design", "usability", "accessibility", "user research",
    "interaction", "journey", "wireframe", "prototype", "heuristic",
  ],
  customer_success: [
    "customer success", "support", "retention", "onboarding", "churn",
    "nps", "voice of customer", "service", "adoption", "renewal",
  ],
  partnerships_growth: [
    "partnership", "alliances", "channel", "ecosystem", "marketplace",
    "affiliate", "co-marketing", "joint venture", "distribution",
  ],
  general_strategy: ["strategy", "business", "planning", "execution", "leadership"],
};

const ACADEMIC_SKILLS_BY_DOMAIN: Record<SkillDomain, readonly string[]> = {
  marketing: [
    "Segmentation, Targeting, and Positioning (STP)",
    "Brand Positioning Strategy",
    "Integrated Marketing Communications (IMC)",
    "Marketing Mix Modeling (MMM)",
    "Customer Lifetime Value (CLV) Analysis",
    "Retention and Cohort Analysis",
    "Conversion Rate Optimization (CRO)",
    "Demand Generation",
    "Performance Marketing",
    "SEO Strategy and Technical SEO",
    "SEM / Paid Search Optimization",
    "Social Media Strategy",
    "Content Strategy",
    "Editorial Calendar Design",
    "Marketing Automation",
    "Lead Nurture Program Design",
    "A/B and Multivariate Testing",
    "Attribution Modeling",
    "Creative Testing Frameworks",
    "Brand Lift Measurement",
    "Go-to-Market (GTM) Planning",
    "Product Marketing Fundamentals",
    "Pricing Communication Strategy",
    "Community-Led Growth",
    "Partnership Marketing",
    "Influencer and Creator Programs",
    "Field Marketing",
    "Event Marketing ROI Analysis",
    "Customer Voice Mining",
    "Marketing Analytics and KPI Design",
    "Campaign Budget Allocation",
    "Market Segmentation Research",
    "Message-Market Fit Validation",
    "Lifecycle Marketing",
  ],
  sales: [
    "Sales Pipeline Design",
    "Pipeline Coverage Analysis",
    "Opportunity Qualification Frameworks",
    "Consultative Selling",
    "Solution Selling",
    "MEDDICC Qualification",
    "SPIN Selling",
    "BANT Qualification",
    "Account-Based Selling (ABS)",
    "Territory Planning",
    "Quota Capacity Planning",
    "Sales Forecasting",
    "Revenue Operations Fundamentals",
    "CRM Data Hygiene Governance",
    "Objection Handling Frameworks",
    "Negotiation Strategy",
    "Procurement Process Navigation",
    "Multi-threading Enterprise Accounts",
    "Executive Discovery Calls",
    "Value-Based Pricing Discussions",
    "Proposal and RFP Management",
    "Sales Enablement Program Design",
    "Onboarding for SDR/BDR Teams",
    "Call Coaching and QA",
    "Win-Loss Analysis",
    "Churn Risk Signals in Sales",
    "Upsell and Cross-Sell Playbooks",
    "Channel and Partner Sales",
    "Sales Compensation Design",
    "Sales Cycle Time Optimization",
    "Deal Desk Governance",
    "Renewal and Expansion Motion",
  ],
  product_management: [
    "Product Discovery Methods",
    "Problem Framing and Opportunity Sizing",
    "Jobs-to-be-Done (JTBD)",
    "North Star Metric Design",
    "Outcome-Driven Roadmapping",
    "RICE Prioritization",
    "MoSCoW Prioritization",
    "Kano Model",
    "PRD Writing",
    "User Story Mapping",
    "Backlog Grooming",
    "Release Planning",
    "Go-to-Market Orchestration",
    "Stakeholder Alignment",
    "Feature Flag Rollout Strategy",
    "Experiment Design for Product Changes",
    "Product Analytics Instrumentation",
    "Funnel and Activation Optimization",
    "Retention Loop Design",
    "Growth Product Tactics",
    "Pricing and Packaging Strategy",
    "Platform Product Strategy",
    "B2B SaaS Product Management",
    "Platform Governance and APIs",
    "Technical Debt Prioritization",
    "Product Risk Management",
    "Accessibility-by-Design",
    "Localization and Internationalization Planning",
    "Competitive Product Benchmarking",
    "MVP Scope Control",
    "Post-Launch Learning Plans",
    "Sunset and Decommission Strategy",
  ],
  data_analytics: [
    "Data Modeling (Star/Snowflake)",
    "Dimensional Modeling",
    "Data Quality Frameworks",
    "Metric Definition Governance",
    "KPI Tree Design",
    "Cohort Analysis",
    "Funnel Analysis",
    "Time-Series Forecasting",
    "Causal Inference",
    "Experimental Design",
    "A/B Test Statistical Analysis",
    "Bayesian Decision Frameworks",
    "Regression Analysis",
    "Classification Modeling",
    "Clustering and Segmentation",
    "Feature Engineering",
    "Data Visualization Principles",
    "Executive Dashboard Design",
    "BI Semantic Layer Modeling",
    "SQL Performance Optimization",
    "Data Pipeline Observability",
    "Data Lineage and Cataloging",
    "Anomaly Detection",
    "Scenario Planning and Simulation",
    "Financial Forecast Analytics",
    "Risk Scoring Models",
    "Survey and Sentiment Analytics",
    "Text Mining/NLP Basics",
    "Sampling Methodology",
    "Research Methods and Validity",
    "Data Storytelling",
    "Decision Intelligence",
  ],
  security_privacy: [
    "Threat Modeling (STRIDE)",
    "Risk Assessment Methodology",
    "Security Architecture Review",
    "Identity and Access Management (IAM)",
    "Least Privilege Enforcement",
    "Zero Trust Principles",
    "Network Segmentation Design",
    "Vulnerability Management Lifecycle",
    "Secure SDLC",
    "DevSecOps Practices",
    "Secrets Management",
    "Encryption at Rest and in Transit",
    "Key Management Lifecycle",
    "Incident Response Planning",
    "Security Monitoring and SIEM",
    "Detection Engineering",
    "Security Logging Standards",
    "Business Continuity and DR Security",
    "Data Privacy Impact Assessment",
    "Privacy-by-Design",
    "Data Retention and Minimization",
    "Vendor Security Assessment",
    "SOC 2 Controls Mapping",
    "ISO 27001 Controls Mapping",
    "NIST CSF Alignment",
    "Penetration Testing Readiness",
    "Red Team / Blue Team Workflows",
    "Abuse and Fraud Prevention",
    "Rate-Limit and Reputation Defenses",
    "Bot Mitigation Strategy",
    "Secure API Design",
    "Compliance Evidence Automation",
  ],
  legal_compliance: [
    "Regulatory Landscape Mapping",
    "Contract Risk Review",
    "Terms of Service Analysis",
    "Data Processing Agreements (DPA)",
    "GDPR Compliance Mapping",
    "CCPA/CPRA Compliance Mapping",
    "Cross-Border Data Transfer Controls",
    "Consent and Preference Management",
    "Policy Drafting",
    "Records of Processing Activities",
    "Compliance Control Framework Design",
    "Audit Readiness Planning",
    "Third-Party Compliance Due Diligence",
    "Licensing Model Analysis",
    "IP Ownership and Assignment Controls",
    "Open Source License Compliance",
    "Marketing Claims Substantiation",
    "Consumer Protection Requirements",
    "Competition/Antitrust Risk Review",
    "Vendor Contract Negotiation Support",
    "Incident Notification Obligations",
    "Accessibility Legal Requirements",
    "Retention and Legal Hold Strategy",
    "Governance Committee Procedures",
    "Compliance Training Program Design",
    "Regulatory Reporting Workflows",
    "Policy Exception Management",
    "Contract Lifecycle Governance",
  ],
  finance_strategy: [
    "Unit Economics Modeling",
    "Gross Margin Analysis",
    "Contribution Margin Analysis",
    "CAC/LTV Analysis",
    "Revenue Recognition Basics",
    "Forecast Model Design",
    "Budget Planning and Controls",
    "Scenario and Sensitivity Analysis",
    "Working Capital Management",
    "Cash Flow Forecasting",
    "Pricing Strategy Economics",
    "Packaging and Monetization Analysis",
    "Cost-to-Serve Analysis",
    "ROI / NPV / IRR Evaluation",
    "Break-even Analysis",
    "Portfolio Prioritization",
    "Capital Allocation Frameworks",
    "Risk-adjusted Planning",
    "Financial KPI Operating Cadence",
    "Board-Level Financial Narratives",
    "FinOps Principles",
    "Cloud Cost Governance",
    "Cost Attribution and Chargeback",
    "Procurement and Vendor Economics",
    "Revenue Operations Alignment",
    "Audit and Internal Controls",
    "Financial Compliance Interfaces",
    "Strategic Planning Cycle Design",
  ],
  operations_delivery: [
    "Program Management",
    "Project Portfolio Management",
    "Agile Delivery Management",
    "Kanban System Design",
    "Critical Path Planning",
    "Risk Register Management",
    "Dependency Mapping",
    "Operational Readiness Reviews",
    "SLA/SLO Definition",
    "Service Management (ITIL) Fundamentals",
    "Incident Command Workflows",
    "Problem Management",
    "Change Management",
    "Release Management",
    "Capacity Planning",
    "Workforce Planning",
    "Process Mapping (BPMN)",
    "Lean Operations",
    "Six Sigma Fundamentals",
    "Quality Assurance Governance",
    "Vendor Operations Management",
    "Runbook Design",
    "Business Continuity Planning",
    "Disaster Recovery Drills",
    "Operational Metrics and OKRs",
    "Support Escalation Design",
    "Knowledge Management",
    "Postmortem Facilitation",
  ],
  ux_research: [
    "User Interviewing",
    "Contextual Inquiry",
    "Surveys and Questionnaire Design",
    "Usability Testing",
    "Heuristic Evaluation",
    "Information Architecture",
    "Interaction Design",
    "Service Blueprinting",
    "Customer Journey Mapping",
    "Persona Development",
    "Accessibility Research",
    "Cognitive Load Analysis",
    "Design System Governance",
    "Wireframing Techniques",
    "High-Fidelity Prototyping",
    "Design Critique Facilitation",
    "Task Flow Optimization",
    "Onboarding UX Optimization",
    "Microcopy and UX Writing",
    "Experimentation in UX",
    "Behavioral Design Patterns",
    "Visual Hierarchy and Readability",
    "Responsive Design Strategy",
    "Error Prevention and Recovery UX",
    "Trust and Safety UX Patterns",
    "Qualitative Insight Synthesis",
    "Research Repository Governance",
    "Design QA and Handoff",
  ],
  customer_success: [
    "Customer Onboarding Program Design",
    "Time-to-Value Optimization",
    "Adoption Playbook Design",
    "Health Score Modeling",
    "Renewal Risk Detection",
    "Expansion Opportunity Mapping",
    "QBR Frameworks",
    "Customer Journey Orchestration",
    "Support Escalation Management",
    "Knowledge Base Strategy",
    "Customer Education Programs",
    "Voice of Customer Programs",
    "NPS/CES Program Design",
    "Churn Analysis",
    "Stakeholder Mapping",
    "Success Plan Design",
    "Implementation Governance",
    "Change Management for Customers",
    "Success Metrics Definition",
    "Account Review Cadence",
    "Customer Advocacy Programs",
    "Reference Program Management",
    "Cross-functional Incident Communication",
    "Service Recovery Frameworks",
  ],
  partnerships_growth: [
    "Partnership Strategy Design",
    "Channel Program Architecture",
    "Co-Selling Motion Design",
    "Alliance Governance",
    "Partner Enablement",
    "Marketplace Listing Strategy",
    "Joint GTM Planning",
    "Affiliate Program Design",
    "Distribution Agreement Structures",
    "Ecosystem Mapping",
    "Partner Segmentation",
    "Revenue Share Model Design",
    "Partner KPI Framework",
    "Incentive Program Design",
    "Partner Onboarding",
    "Co-Marketing Execution",
    "Partnership Risk Governance",
    "API Partner Programs",
    "Integration Partnership Planning",
    "Strategic Alliance Negotiation",
    "Network Effects Analysis",
    "Growth Loop Partnerships",
    "Market Entry via Partnerships",
    "Partner Performance Management",
  ],
  general_strategy: [
    "Strategic Problem Structuring",
    "Decision Framing",
    "Hypothesis-Driven Planning",
    "Scenario Planning",
    "Organizational Design",
    "Stakeholder Communication",
    "Cross-Functional Alignment",
    "Change Leadership",
    "Execution Governance",
    "Risk-Based Prioritization",
    "Performance Management",
    "Operating Model Design",
    "Roadmap Governance",
    "Strategic Narrative Development",
    "Outcome-Based Planning",
    "Capability Maturity Assessment",
    "Benchmarking Methods",
    "Portfolio Governance",
    "Strategic KPI Design",
    "Implementation Planning",
  ],
};

const GENERAL_ACADEMIC_SKILLS = [
  "Critical Thinking",
  "Structured Problem Solving",
  "Systems Thinking",
  "Quantitative Analysis",
  "Research Design",
  "Statistical Literacy",
  "Risk Management Fundamentals",
  "Stakeholder Management",
  "Executive Communication",
  "Negotiation Fundamentals",
  "Ethics and Responsible Decision-Making",
  "Governance Design",
  "Process Improvement",
  "Data Literacy",
  "Decision Documentation",
  "Root Cause Analysis",
  "Scenario Analysis",
  "Operational Planning",
  "Continuous Improvement",
  "Program Evaluation",
] as const;

const ACADEMIC_POOL_LIMIT = 72;
const ACADEMIC_TOP_CHOICES = 24;
const ACADEMIC_RANKING_BASIS =
  `${POPULARITY_RELIABILITY_BASIS} + academic relevance by persona discipline.`;

function dedupeKeepOrder(items: readonly string[]): string[] {
  const seen = new Set<string>();
  const output: string[] = [];

  for (const item of items) {
    const key = item.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    output.push(item);
  }

  return output;
}

function scoreDomain(text: string, domain: SkillDomain): number {
  return ACADEMIC_SKILL_DOMAIN_KEYWORDS[domain].reduce((score, keyword) => {
    if (!keyword) return score;
    return text.includes(keyword) ? score + 1 : score;
  }, 0);
}

export function detectPersonaSkillDomain(persona: Pick<PersonaWithCatalog, "id" | "name" | "reason" | "initialThought">): SkillDomain {
  const corpus = `${persona.id} ${persona.name} ${persona.reason} ${persona.initialThought}`
    .toLowerCase();

  let bestDomain: SkillDomain = "general_strategy";
  let bestScore = 0;

  const domains = Object.keys(ACADEMIC_SKILL_DOMAIN_KEYWORDS) as SkillDomain[];
  for (const domain of domains) {
    const domainScore = scoreDomain(corpus, domain);
    if (domainScore > bestScore) {
      bestDomain = domain;
      bestScore = domainScore;
    }
  }

  return bestScore > 0 ? bestDomain : "general_strategy";
}

export function attachAcademicSkillCatalog<T extends PersonaWithCatalog>(persona: T): T {
  if (Array.isArray(persona.candidatePool) && persona.candidatePool.length > 0) {
    return persona;
  }

  const domain = detectPersonaSkillDomain(persona);
  const domainSkills = ACADEMIC_SKILLS_BY_DOMAIN[domain] ?? [];
  const merged = dedupeKeepOrder([...domainSkills, ...GENERAL_ACADEMIC_SKILLS]);

  return {
    ...persona,
    skillDomain: domain,
    candidateCatalogType: "academic_skills",
    candidatePool: merged.slice(0, ACADEMIC_POOL_LIMIT),
    candidateTopChoices: merged.slice(0, ACADEMIC_TOP_CHOICES),
    rankingBasis: ACADEMIC_RANKING_BASIS,
  };
}
